version: '1'

services:
  redis:
    image: redis:7.4.0-alpine
    container_name: redis
    hostname: redis
    ports:
      - '6379:6379'

  postgres:
    image: postgres:14.15-alpine3.21
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: travel_agent