package com.halcyon.travelagent.caching;

public enum ChatStatusType {
    TRAVEL_NAME,
    TRAVEL_DESCRIPTION,
    LOCATION_CITY,
    LOCATION_STREET,
    LOCATION_START_TIME,
    LOCATION_END_TIME,
    CHOICE_OF_LOCATIONS,
    CHANGE_LOCATION_CITY,
    CHANGE_LOCATION_START_TIME,
    CHANGE_LOCATION_END_TIME,
    ROUTE_START_POINT,
    ROUTE_DESTINATION_POINT,
    ROUTE_NAME
}
